// Convert the TUMFTM Interlagos centreline (assets-src/SaoPaulo.csv: x_m, y_m, w_tr_right_m, w_tr_left_m)
// into src/world/circuits/interlagosLine.ts: x = east, z = −y (south), centred on the bounding box,
// index rotated so s = 0 sits on the run from Mergulho down to Junção (the pit lane never wraps).
//
//   node tools/interlagosLine.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const rows = readFileSync('assets-src/SaoPaulo.csv', 'utf8')
  .split('\n')
  .filter((l) => l.trim() && !l.startsWith('#'))
  .map((l) => l.split(',').map(Number));
const m = rows.length;
// the survey runs anticlockwise (positive shoelace area with y = north), as the race does
let area = 0;
for (let i = 0; i < m; i++) {
  const a = rows[i], b = rows[(i + 1) % m];
  area += a[0] * b[1] - b[0] * a[1];
}
if (area < 0) rows.reverse();
let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity;
for (const [x, y] of rows) {
  x0 = Math.min(x0, x); x1 = Math.max(x1, x);
  y0 = Math.min(y0, y); y1 = Math.max(y1, y);
}
const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;
// rotate: the first point at START_S metres along the survey (measured from the CSV's first point,
// which sits on the start/finish line)
const START_S = 3100;
let cum = 0, k0 = 0;
for (let i = 0; i < m; i++) {
  if (cum >= START_S) { k0 = i; break; }
  const a = rows[i], b = rows[(i + 1) % m];
  cum += Math.hypot(b[0] - a[0], b[1] - a[1]);
}
const pts = [];
for (let j = 0; j < m; j++) {
  const [x, y] = rows[(k0 + j) % m];
  pts.push((x - cx).toFixed(2), (-(y - cy)).toFixed(2));
}
let body = '';
for (let i = 0; i < pts.length; i += 16) body += '  ' + pts.slice(i, i + 16).join(', ') + ',\n';
const ts = `/**
 * Autódromo José Carlos Pace, Interlagos — surveyed centreline (the Grand Prix layout).
 *
 * Derived from the TUMFTM racetrack-database (github.com/TUMFTM/racetrack-database,
 * LGPL-3.0), which traces the circuit from satellite imagery. Points are ~5 m
 * apart, in driving order (anticlockwise), world metres: x = east, z = south,
 * centred on the circuit's bounding box. Index 0 sits on the run from Mergulho
 * down to Junção, so the pit lane (inside the main straight) never wraps; the
 * start/finish line is at s ≈ ${Math.round(4304.6 - cum)}.
 *
 * Generated by tools/interlagosLine.mjs from assets-src/SaoPaulo.csv.
 */
// prettier-ignore
export const INTERLAGOS_LINE: number[] = [
${body}];
`;
writeFileSync('src/world/circuits/interlagosLine.ts', ts);
console.log('points', m, 'rotated by', k0, 'start line at s ≈', (cum > 0 ? 4304.6 - cum : 0).toFixed(1));
