// Convert the TUMFTM Spielberg CSV into src/world/circuits/spielbergLine.ts
//   node tools/spielberg_line.mjs [startIndex] [--analyse]
// x = east, z = −y (south), centred on the bounding box, index rotated so s = 0 is
// on the run from Turn 9 to Turn 10 (the pit lane, entry after T10, exit after T1, never wraps).
import fs from 'node:fs';

const src = fs.readFileSync(new URL('../assets-src/Spielberg.csv', import.meta.url), 'utf8');
const rows = src.split('\n').filter((l) => l.trim() && !l.startsWith('#')).map((l) => l.split(',').map(Number));
let pts = rows.map(([x, y, wr, wl]) => ({ x, z: -y, wr, wl }));
const start = Number(process.argv[2] ?? 0);
pts = [...pts.slice(start), ...pts.slice(0, start)];
let x0 = Infinity, x1 = -Infinity, z0 = Infinity, z1 = -Infinity;
for (const p of pts) { x0 = Math.min(x0, p.x); x1 = Math.max(x1, p.x); z0 = Math.min(z0, p.z); z1 = Math.max(z1, p.z); }
const cx = (x0 + x1) / 2, cz = (z0 + z1) / 2;
for (const p of pts) { p.x -= cx; p.z -= cz; }

if (process.argv.includes('--analyse')) {
  // cumulative s, heading, curvature (smoothed) and a list of corners
  const n = pts.length;
  const s = [0];
  for (let i = 1; i <= n; i++) s.push(s[i - 1] + Math.hypot(pts[i % n].x - pts[i - 1].x, pts[i % n].z - pts[i - 1].z));
  const th = pts.map((p, i) => { const q = pts[(i + 1) % n]; return Math.atan2(q.x - p.x, q.z - p.z); });
  const wrap = (a) => { while (a > Math.PI) a -= 2 * Math.PI; while (a < -Math.PI) a += 2 * Math.PI; return a; };
  const k = th.map((t, i) => wrap(t - th[(i - 1 + n) % n]) / 5);
  const ks = k.map((_, i) => { let a = 0; for (let d = -3; d <= 3; d++) a += k[(i + d + n) % n]; return a / 7; });
  let tot = 0; for (const v of k) tot += v * 5;
  console.log('points', n, 'length', s[n].toFixed(1), 'total turn deg', (tot * 180 / Math.PI).toFixed(1), 'bbox', (x1 - x0).toFixed(0), (z1 - z0).toFixed(0));
  for (let i = 0; i < n; i += 4) {
    const bar = '#'.repeat(Math.min(60, Math.round(Math.abs(ks[i]) * 2000)));
    console.log(String(Math.round(s[i])).padStart(5), pts[i].x.toFixed(0).padStart(5), pts[i].z.toFixed(0).padStart(5), (th[i] * 180 / Math.PI).toFixed(0).padStart(5), (ks[i] > 0 ? '+' : '-'), bar, 'w', pts[i].wr.toFixed(1), pts[i].wl.toFixed(1));
  }
  process.exit(0);
}

const lines = [];
for (let i = 0; i < pts.length; i += 8) lines.push('  ' + pts.slice(i, i + 8).map((p) => `${p.x.toFixed(2)}, ${p.z.toFixed(2)}`).join(', ') + ',');
const out = `/**
 * Red Bull Ring, Spielberg — surveyed centreline (the Grand Prix layout since 2016).
 *
 * Derived from the TUMFTM racetrack-database (github.com/TUMFTM/racetrack-database,
 * LGPL-3.0), which traces the circuit from satellite imagery. Points are ~5 m
 * apart, in driving order (clockwise), world metres: x = east, z = south,
 * centred on the circuit's bounding box. Index 0 sits on the run from Turn 9
 * down to the last corner, so the pit lane (entry after Turn 10, exit after
 * Turn 1) never wraps. Generated by tools/spielberg_line.mjs.
 */
// prettier-ignore
export const SPIELBERG_LINE: number[] = [
${lines.join('\n')}
];
`;
fs.writeFileSync(new URL('../src/world/circuits/spielbergLine.ts', import.meta.url), out);
console.log('wrote', pts.length, 'points');
